#-------------------#
# Everything Config #
#-------------------#

#-------#
# Notes #
#-------#

# When configuring this file:

# Do NOT use tab, use standard spaces (2 spaces are roughly equal to a tab)
# To avoid this, I recommend using Notepad++ over the standard Notepad (Google it if you don't already have it)
# When using Notepad++ you can change tabs to be replaced by a configurable number of spaces by going to the
# Settings tool bar option, then to Preferences and finally to Language Menu/Tab Settings.

# Do NOT change the format of the files; i.e. if an option is indented, don't remove the indentation.

# If you want to add extra information for extra ease of use; all comment lines should start with a hashtag.
    # Hopefully adding extra comments should be unneseccary as I
    # Aim to keep this config file as well explained as I can.

# When changing strings (such as messages to players), make sure any apostrophes are "escaped"; i.e. "can''t"
# Rather than "can't" - rather than one apostrophe, use two.

# For any number values never include decimals if they are not initially provided (i.e. 20 should not
# be changed to 20.1 or 20.1234)

#-----------------#
# Config Settings #
#-----------------#

# This will determine the default time, in seconds, that a player will burn for when the command "/burn
# <PlayerName> <Burn Time>" is used on them without a set time duration (<Burn Time>).
defaultburntime: 20

# This will determine the default time, in seconds, that a player will burn for when the command "/fire
# <PlayerName> <Burn Time> <Area of Effect>" is used on them without a set time duration.
defaultfiretime: 20

# This will determine the default size, in blocks, that the fire will spreadover when the command "/fire
# <PlayerName> <Burn Time> <Area of Effect>" is used on them without a set area of effect.
defaultfiresize: 5