main: com.bossomeness.everything.in.one.plugin.Everything
name: EverythingPlugin
version: 0.1
description: everything in one plugin!
commands:
    Everything:
        description: This command is the basis of all commands in the Everything Plugin.
        aliases: EV